apiVersion: batch/v1
kind: Job
metadata:
  name: realm-job-{{ template "alfresco-identity.fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install #Determines time of deploy
    "helm.sh/hook-weight": "-5" #Determines the order if multiple hooks are deffined
    "helm.sh/hook-delete-policy": hook-succeeded #Determines when is the object deleted
spec:
  template:
    metadata:
      name: realm-job-pod-{{ template "alfresco-identity.fullname" . }}
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: "{{ .Values.hyperkube.image.repository }}:{{ .Values.hyperkube.image.tag }}"
        imagePullPolicy: "{{ .Values.hyperkube.image.pullPolicy }}"
        command: ["bash","-c","/scripts/realm_install.sh app=keycloak,release={{ .Release.Name }} {{ index .Values.keycloak.keycloak.ingress.hosts 0 }} "]
        env:
          - name: KEYCLOAKUSERNAME
            value: {{ .Values.keycloak.keycloak.username }}
          - name: KEYCLOAKSECRET
            valueFrom:
              secretKeyRef:
                name: keycloak-{{ .Release.Name | trunc 11 | trimSuffix "-"}}-http
                key: password
        volumeMounts:
            - name: scripts-{{ template "alfresco-identity.fullname" . }}
              mountPath: /scripts
            - name: realm-secret-{{ template "alfresco-identity.fullname" . }}
              mountPath: /realmsecret
              readOnly: true
      volumes:
        - name: realm-secret-{{ template "alfresco-identity.fullname" . }}
          secret:
             {{- if eq .Values.keycloak.secretName "none" }}
             secretName: realm-secret-{{ template "alfresco-identity.fullname" . }}
             {{- else }}
             secretName: .Values.keycloak.secretName
             {{- end }}
        - name: scripts-{{ template "alfresco-identity.fullname" . }}
          configMap:
             name: realm-config-{{ template "alfresco-identity.fullname" . }}
             items:
              - key: realm_install.sh
                path: realm_install.sh
                mode: 0755
