apiVersion: batch/v1
kind: Job
metadata:
  name: rb-clean-{{ template "alfresco-identity.fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-rollback #Determines time of deploy
    "helm.sh/hook-weight": "0" #Determines the order if multiple hooks are deffined
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed #Determines when is the object deleted
spec:
  template:
    metadata:
      name: rb-clean-{{ template "alfresco-identity.fullname" . }}
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      restartPolicy: "OnFailure"
      containers:
        - name: rb-clean
          image: "{{ .Values.hyperkube.image.repository }}:{{ .Values.hyperkube.image.tag }}"
          imagePullPolicy: "{{ .Values.hyperkube.image.pullPolicy }}"
          command:
            - bash
            - -c
            - |
              kubectl get sts
              kubectl delete --ignore-not-found sts {{ template "keycloak.fullname" . }}
              kubectl delete --ignore-not-found sts {{ .Release.Name }}-{{ .Values.keycloak.postgresql.nameOverride }}
              sleep 5
              kubectl get sts

---

apiVersion: batch/v1
kind: Job
metadata:
  name: rb-stopkc-{{ template "alfresco-identity.fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-rollback #Determines time of deploy
    "helm.sh/hook-weight": "1" #Determines the order if multiple hooks are deffined
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded #Determines when is the object deleted
spec:
  template:
    metadata:
      name: rb-stopkc-{{ template "alfresco-identity.fullname" . }}
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      restartPolicy: "OnFailure"
      containers:
        - name: rb-stopkc
          image: "{{ .Values.hyperkube.image.repository }}:{{ .Values.hyperkube.image.tag }}"
          imagePullPolicy: "{{ .Values.hyperkube.image.pullPolicy }}"
          command:
            - bash
            - -c
            - |
              kubectl get sts
              kubectl scale --replicas=0 statefulset/{{ template "keycloak.fullname" . }}
              sleep 3
              kubectl delete --ignore-not-found pod {{ template "keycloak.fullname" . }}-0

---

apiVersion: batch/v1
kind: Job
metadata:
  name: rb-restore-{{ template "alfresco-identity.fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-rollback #Determines time of deploy
    "helm.sh/hook-weight": "2" #Determines the order if multiple hooks are deffined
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded #Determines when is the object deleted
spec:
  template:
    metadata:
      name: rb-restore-{{ template "alfresco-identity.fullname" . }}
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      restartPolicy: "OnFailure"
      containers:
        - name: rb-restore
          image: "postgres:11.1"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.keycloak.postgresql.nameOverride }}
                  key: postgresql-password
          command:
            - bash
            - -c
            - |
              psql -h {{ .Release.Name }}-{{ .Values.keycloak.postgresql.nameOverride }} \
              -p {{ .Values.keycloak.postgresql.service.port }} \
              -d keycloak \
              -U {{ .Values.keycloak.keycloak.persistence.dbUser }} -f /backup/backup.sql
          volumeMounts:
          - name: data
            mountPath: "/backup"
            subPath: "{{ .Values.keycloak.postgresql.persistence.subPath }}-backup"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: backup-{{ template "alfresco-identity.fullname" . }}

---

apiVersion: batch/v1
kind: Job
metadata:
  name: rb-startkc-{{ template "alfresco-identity.fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-rollback #Determines time of deploy
    "helm.sh/hook-weight": "3" #Determines the order if multiple hooks are deffined
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded #Determines when is the object deleted
spec:
  template:
    metadata:
      name: rb-startkc-{{ template "alfresco-identity.fullname" . }}
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      restartPolicy: "OnFailure"
      containers:
        - name: rb-startkc
          image: "{{ .Values.hyperkube.image.repository }}:{{ .Values.hyperkube.image.tag }}"
          imagePullPolicy: "{{ .Values.hyperkube.image.pullPolicy }}"
          command:
            - bash
            - -c
            - |
              kubectl get sts
              kubectl scale --replicas=1 statefulset/{{ template "keycloak.fullname" . }}
              sleep 3
              kubectl delete --ignore-not-found pod {{ template "keycloak.fullname" . }}-0
